import { ICar } from '../types';

export function prepareDataObj(data: ICar) {
  for (const key in data) {
    if (data[key as keyof typeof data] === '') delete data[key as keyof typeof data];
  }
  return data;
}

export function setLogo(logo: string) {
  const logoName = logo.split(' ')[0].toLowerCase() as string;
  const brands = [
    'alfa',
    'aro',
    'aston',
    'audi',
    'avia',
    'bentley',
    'bmw',
    'bristol',
    'bugatti',
    'buick',
    'cadillac',
    'chatenet',
    'chevrolet',
    'chrysler',
    'citroen',
    'cupra',
    'dacia',
    'daewoo',
    'daf',
    'daihatsu',
    'datsun',
    'dodge',
    'ferrari',
    'fiat',
    'ford',
    'gordon',
    'great',
    'gumpert',
    'holden',
    'honda',
    'hummer',
    'hyundai',
    'infiniti',
    'invicta',
    'isuzu',
    'iveco',
    'jaguar',
    'jeep',
    'kaipan',
    'kia',
    'knaus',
    'koenigsegg',
    'lada',
    'lamborghini',
    'lancia',
    'land',
    'lexus',
    'liaz',
    'lincoln',
    'magma',
    'mahindra',
    'man',
    'maserati',
    'matra',
    'mazda',
    'mclaren',
    'mercedes',
    'mg',
    'mini',
    'mitsubishi',
    'москвич',
    'multicar',
    'nissan',
    'oltcit',
    'opel',
    'peugot',
    'pgo',
    'phanomen',
    'pontiac',
    'porsche',
    'praga',
    'renault',
    'rolls',
    'rover',
    'saab',
    'saleen',
    'seat',
    'simca',
    'skoda',
    'smart',
    'ssangyong',
    'subaru',
    'suzuki',
    'tatra',
    'tesla',
    'toyota',
    'trabant',
    'venturi',
    'volvo',
    'vw',
    'wartburg',
    'wiesmann',
    'volkswagen',
  ];
  return `${brands.includes(logoName) ? logoName : 'other-car'}`;
}
